spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankingdb
    username: mefind
    password: mefind!Q@W#E4r
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: be.kangyongho
  paths-to-match: /**
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 8080

logging:
  level:
    root: INFO
    be.kangyongho: DEBUG
    org.hibernate: INFO
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.http: TRACE
    org.springframework.web.servlet.mvc.method.annotation: TRACE