spring:
  datasource:
    url: jdbc:postgresql://db:5432/bankingdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: be.kangyongho
  paths-to-match: /api/**
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 8080

logging:
  level:
    root: INFO
    be.kangyongho: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG